# Generated by Django 5.2.7 on 2025-11-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_generatedimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='image_url',
            field=models.URLField(default='https://example.com/placeholder.png'),
        ),
    ]
